# Generated by Django 3.2.5 on 2021-07-04 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmsslider',
            name='cms_css',
            field=models.CharField(default='---', max_length=100, null=True),
        ),
    ]
