# Generated by Django 3.2.5 on 2021-07-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telesettings',
            name='tg_text',
            field=models.TextField(verbose_name='Text'),
        ),
    ]
