# Generated by Django 3.2.5 on 2021-07-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_comentcrm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comentcrm',
            options={'verbose_name': 'Комент', 'verbose_name_plural': 'Коменты'},
        ),
    ]
