# Generated by Django 3.2.5 on 2021-07-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_comentcrm_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentcrm',
            name='coment_data',
            field=models.DateTimeField(auto_now=True, verbose_name='Last changes'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_dt',
            field=models.DateTimeField(auto_now=True, verbose_name='Время регистрации'),
        ),
    ]
